### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by slow** [MulverineX/premid-powercord#4]
invalid import at [Line 22](https://github.com/MulverineX/premid-powercord/blob/master/src/activity.js#L22)
crashes at [Line 80](https://github.com/MulverineX/premid-powercord/blob/master/src/activity.js#L80) when changing the invalid module to `SET_ACTIVITY` from `INVITE_BROWSER`

**Comment by MulverineX** [comment]
Thanks for porting the fix over, I had talked with e-boi about it already but hadn't gotten to it
